Resources/en.lproj/Localizable.strings, Sources/VLCOpenNetworkStreamViewController.m
We're also showing an alert when the user enters a wrong url now
=> fix crash on bad url

Podfile, Podfile.lock, README.md
=> Small fixes regarding Cocoapods 🍫

Sources/VLCMovieViewController.m
They don't seem to be used anymore but I might miss something so let me know
=> remove not needed UIAlertSheets and UIPopoverController

SharedSources/MediaDataSourceAndDelegate.swift, SharedSources/PresentationTheme.swift, Sources/BaseButtonBarPagerTabStripViewController.swift, Sources/ButtonBarView.swift, Sources/Coordinators/AppCoordinator.swift, Sources/Coordinators/SortOption.swift, Sources/LocalNetworkConnectivity/RemoteNetworkDataSource.swift, Sources/MediaViewController.swift, Sources/PagerStripViewController.swift, Sources/VLCActionSheet/VLCActionSheet.swift, Sources/VLCDocumentPickerController.m, Sources/VLCTabBarCoordinator.swift, fastlane/SnapshotHelper.swift
It was a bit bugging me during medialibrary work! 😄
=> Remove unnecessary public & open

Sources/VLCAppDelegate.m, Sources/VLCDocumentClass.swift, Sources/VLCPlaybackController.h, Sources/VLCPlaybackController.m, Sources/VLCRendererDiscovererManager.swift, VLC.xcodeproj/project.pbxproj
This fixes all the open in Issues while still working with the Files app
=> Vlc open in fix

Sources/VLCActionSheet/VLCActionSheet.swift, fastlane/Fastfile
=> CircleCI: remove explicit Xcode version

SharedSources/VLCAlertViewController.swift, Sources/LocalNetworkConnectivity/VLCNetworkServerBrowserViewController.m, Sources/VLCBoxTableViewController.m, Sources/VLCBugreporter.m, Sources/VLCDropboxTableViewController.m, Sources/VLCGoogleDriveTableViewController.m, Sources/VLCOneDriveTableViewController.m, Sources/VLCPlaybackController.m
Minor addition of `style` parameter to `VLCAlertButton`_(change need for my medialibrary branch)._ 😄
Additionally a bit of cosmetic changes.
=>  VLCAlertViewController: VLCAlertButton: Add style parameter

VLC.xcodeproj/xcshareddata/xcschemes/VLC-iOS.xcscheme
=> Tests: enable testCaptureVideoPlayback again

Sources/MediaCategories/MediaCategory.swift
(closes #294)
This updates **only** the view. The logic for handling/filtering video, audio, mixed playlist will be addressed by another PR.
=> VLCAudioPlaylistCategoryViewController: Use PlaylistModel

vlc-ios/Images.xcassets/AppIcon.appiconset/Contents.json, vlc-ios/Images.xcassets/Library View/folderIcon.imageset/Contents.json, vlc-ios/Images.xcassets/Library View/gradient-cell-ios7.imageset/Contents.json, vlc-ios/Images.xcassets/Library View/tvShow.imageset/Contents.json, vlc-ios/Images.xcassets/PlayingExternally.imageset/Contents.json, vlc-ios/Images.xcassets/TVBroadcastIcon.imageset/Contents.json, vlc-ios/Images.xcassets/cloudServices/audio.imageset/Contents.json, vlc-ios/Images.xcassets/cloudServices/blank.imageset/Contents.json, vlc-ios/Images.xcassets/cloudServices/folder.imageset/Contents.json, vlc-ios/Images.xcassets/cloudServices/movie.imageset/Contents.json, vlc-ios/Images.xcassets/menu/serverIcon.imageset/Contents.json
=> Xcode: Automatic images xcassets adjustment

Gemfile.lock
Received a kind email saying that there is a vulnerability with 1.2.1
ref: [CVE-2018-1000544](https://nvd.nist.gov/vuln/detail/CVE-2018-1000544)
=> Gemfile.lock: Update rubyzip to 1.2.2

SharedSources/VLCMediaLibraryManager.swift, Sources/Coordinators/AppCoordinator.swift, Sources/VLCAppDelegate.m, Sources/VLCMigrationViewController.h, Sources/VLCMigrationViewController.m, VLC-iOS-Bridging-Header.h
Basic migration of MLLabels and MLFiles.
Small note: This need a fresh build of VLCMediaLibraryKit to work since the changes haven't been released yet.
=> VLCMediaLibraryManager: Basic migration of MLLabels and MLFiles

Resources/PlaybackSpeedView.xib, Resources/VLCMovieViewController.xib, Sources/VLCMovieViewController.m
=> MovieViewcontroller: readd Outlet to avoid crash when starting a video

Sources/VLCRendererDiscovererManager.swift
=> Fix rendererButton size to 44x44

Sources/VLCMigrationViewController.m, Sources/VLCMigrationViewController.xib
The old background was always a dark colour which led to a flash with the white theme.
=> Change the MigrationVC background color for new UI

Sources/MediaCategories/MediaCategory.swift, Sources/MediaCategories/MediaCategoryViewController.swift, Sources/VLCEditController.swift
=> Cosmetic: Rename category to model

Sources/MediaCategories/MediaCategoryViewController.swift, Sources/VLCEditToolbar.swift
=> Minor UI adjustment for EditToolbar

Sources/MediaCategories/MediaCategoryViewController.swift, Sources/MediaCategoryCells/MovieCollectionViewCell.xib
This doesn't address the cell sizing issue.
=> Minor MovieCollectionViewCell updates according to new design

Sources/Coordinators/AppCoordinator.swift
=> AppCoordinator: Migration: Present and dismiss on main thread

SharedSources/MediaLibraryModel/AlbumModel.swift, SharedSources/MediaLibraryModel/ArtistModel.swift, SharedSources/MediaLibraryModel/AudioModel.swift, SharedSources/MediaLibraryModel/GenreModel.swift, SharedSources/MediaLibraryModel/MediaLibraryBaseModel.swift, SharedSources/MediaLibraryModel/PlaylistModel.swift, SharedSources/MediaLibraryModel/ShowEpisodeModel.swift, SharedSources/MediaLibraryModel/VideoModel.swift, SharedSources/MediaLibraryService.swift, Sources/Coordinators/AppCoordinator.swift, VLC.xcodeproj/project.pbxproj
=> VLCMediaLibraryManager: Rename to MediaLibraryService

Podfile, Podfile.lock, Resources/en.lproj/Localizable.strings, SharedSources/MediaLibraryModel/AlbumModel.swift, SharedSources/MediaLibraryModel/ArtistModel.swift, SharedSources/MediaLibraryModel/CollectionModel.swift, SharedSources/MediaLibraryModel/GenreModel.swift, SharedSources/MediaLibraryModel/MediaLibraryBaseModel.swift, SharedSources/MediaLibraryModel/MediaModel.swift, SharedSources/MediaLibraryModel/PlaylistModel.swift, SharedSources/MediaLibraryModel/ShowEpisodeModel.swift, SharedSources/MediaLibraryModel/TrackModel.swift, SharedSources/MediaLibraryService.swift, Sources/MediaCategories/MediaCategory.swift, Sources/MediaCategoryCells/MediaCollectionViewCell.swift, Sources/MediaCategoryCells/MovieCollectionViewCell.swift, Sources/MediaEditCell.swift, Sources/VLCEditController.swift, VLC.xcodeproj/project.pbxproj
Adapt to nullability changes from VLCMediaLibraryKit 0.2.0.
Additionally, refactor createPlaylist from models to EditController.
=>  Adapt to nullability changes from VLCMediaLibraryKit 0.2.0 

Sources/ActionSheet/ActionSheet.swift
Addresses [#486](https://code.videolan.org/videolan/vlc-ios/issues/486) & [#487](https://code.videolan.org/videolan/vlc-ios/issues/487)
=> ActionSheet: Fix flickering & delegate

Resources/Xib/AddToPlaylist/AddToPlaylistView.xib, Resources/en.lproj/Localizable.strings, Sources/AddToPlaylistViewController.swift
=> AddToPlaylistViewController: Place new playlist button below collectionView

Sources/MediaCategoryCells/MediaCollectionViewCell.swift, Sources/MediaCategoryCells/MovieCollectionViewCell.swift
=> MediaCollectionViewCell: Set thumbnails for collections

Resources/Xib/AddToPlaylist/AddToPlaylistView.xib
=> AddToPlaylistViewController: Add bottom margin

Resources/en.lproj/Localizable.strings, Sources/EditToolbar.swift, Sources/MediaCategories/MediaCategoryViewController.swift, Sources/VLCEditController.swift, Sources/VLCEditToolbar.swift, VLC.xcodeproj/project.pbxproj
Minor adjustment to the design(font style & order) and add accessibility.
I decided to not separate the PR into multiple since it included the refactoring(renaming).
If needed I do not mind creating multiple PRs!
Additionally, for the accessibility, I didn't have a lot of ideas for hints and labels. Ideas welcome!
=> EditToolbar: Adjustment to design

Sources/MediaCategories/MediaCategoryViewController.swift
Related issue [492](https://code.videolan.org/videolan/vlc-ios/issues/492).
Assertions could be considered when the files are nil.
=> VLCMediaCategoryViewController: Handle AutomaticallyPlayNextItem setting

Sources/MediaEditCell.swift, Sources/VLCEditController.swift
=> EditController: Have multiple cells in one line

Sources/VLCHTTPConnection.m
Closes ![#520](https://code.videolan.org/videolan/vlc-ios/issues/520).
=> WiFi Sharing: Thumbnail Fix

Sources/VLCHTTPConnection.m
Closes ![#538](https://code.videolan.org/videolan/vlc-ios/issues/538).
=> VLCHTTPConnection: Fix album tracks listing

Sources/MediaCategories/MediaCategoryViewController.swift, Sources/VLCEditController.swift
Reset selection after playlist addition with minor refactoring.
=> Edit: Reset selection after playlist addition

Sources/MediaEditCell.swift
=> MediaeditCell: Handle Unknown and Various artist

Sources/MediaCategoryCells/MediaCollectionViewCell.xib
Fix constraint on the stackView and set by default the content mode to `.scaleAspectFill`.
=> MediaCollectionViewCell: xib: Fix constraint and image behaviour

Sources/VLCCloudStorageTableViewController.m
=> VLCCloudStorageTableViewController: Update progressLabel color

Sources/EditController.swift
Quick and straight forward patch that adds the possibility to add any collection(artist, album, genre, ...) to a playlist.
=> EditController: Playlist: Handle collection addition

Resources/en-GB.lproj/Localizable.strings
=> Update English UK strings

Sources/VLCCloudStorageController.h, Sources/VLCCloudStorageController.m, Sources/VLCDropboxController.m, Sources/VLCOneDriveController.m
VLCOneDriveController: Fix download by using OneDriveSDK
[Closes #594](https://code.videolan.org/videolan/vlc-ios/issues/594)
=> VLCOneDriveController: Fix download by using OneDriveSDK

Sources/VLCCloudStorageTableViewController.m
=> VLCCloudStorageTableViewController: Set preferredStatusBarStyle

Sources/MediaCategoryCells/MediaCollectionViewCell.swift
Reduce by 20 to be in sync with movies.
Tested on iPhone X and iPad Pro(12.9 inch):
Before:
https://i.gyazo.com/4043ae6bb2736a320d7687c35e540cd7.png
https://i.gyazo.com/f063e8d8af251f42ece3d5ae84818b94.png
https://i.gyazo.com/e6c225ad8a8ed6d72e2856cff00b8ba6.png
After:
https://i.gyazo.com/c3495c1a0726f2bcb27dbaa7ea4738c3.png
https://i.gyazo.com/4152860d1ce32b925306d34566651706.png
https://i.gyazo.com/ead9afe4306e8aaaa69a432f5ab356ef.png
=> MediaCollectionViewCell: Reduce margin height

Sources/VLCSettingsController.m
This led to colours not being correctly updated issues.
The registration is handled inside ActionSheet.
=> VLCSettingsController: Remove unnecessary cell registration

Sources/LocalNetworkConnectivity/VLCNetworkServerBrowserViewController.m
=> VLCNetworkServerBrowserViewController: Set preferredStatusBarStyle

Sources/LocalNetworkConnectivity/VLCNetworkLoginViewController.m
=> VLCNetworkLoginViewController: Set preferredStatusBarStyle

Sources/LocalNetworkConnectivity/RemoteNetworkDataSource.swift
=> RemoteNetworkDataSource: Set Wifi cell height according to design

Sources/LocalNetworkConnectivity/VLCServerListViewController.m, Sources/VLCBoxTableViewController.m, Sources/VLCCloudServicesTableViewController.m, Sources/VLCDropboxTableViewController.m, Sources/VLCGoogleDriveTableViewController.m, Sources/VLCOneDriveTableViewController.m
There is a bit of back or forth in the willAppear in order to maintain the large title in views that needs and views that doesn't.
Open for better ideas. 😄 
(closes #597)
=> Network: Set prefersLargeTitles according to design

Sources/KeychainCoordinator.swift, Sources/LocalNetworkConnectivity/VLCServerListViewController.m, Sources/VLCBoxTableViewController.m, Sources/VLCCloudServicesTableViewController.m, Sources/VLCDropboxTableViewController.m, Sources/VLCGoogleDriveTableViewController.m, Sources/VLCOneDriveTableViewController.m
=> PAPasscodeViewController: Extend to set preferredStatusBarStyle

SharedSources/MediaLibraryService.swift
=> MediaLibraryService: Call correct delegate method didModifyAlbums

Sources/VLCCloudStorageTableViewController.m, Sources/VLCDropboxController.m
=> VLCDropboxController: Reset correctly on logout

SharedSources/MediaLibraryModel/PlaylistModel.swift, Sources/EditController.swift
Closes [#603](https://code.videolan.org/videolan/vlc-ios/issues/603).
=> Edit: Fix rename for playlists

SharedSources/MediaLibraryModel/CollectionModel.swift, SharedSources/MediaLibraryService.swift, Sources/MediaCategories/MediaCategory.swift, Sources/MediaCategories/MediaCategoryViewController.swift, Sources/MediaViewControllers/AudioViewController.swift, Sources/MediaViewControllers/MediaViewController.swift, Sources/MediaViewControllers/PlaylistViewController.swift, Sources/MediaViewControllers/VideoViewController.swift
=> Cosmetic - Rename: Batch 

Sources/VLCMovieViewController.m
Closes [#617](https://code.videolan.org/videolan/vlc-ios/issues/617).
=> VLCMovieViewController: Fix iPad multiSelectionView frame

Sources/MediaCategories/MediaCategoryViewController.swift, Sources/MediaViewControllers/MediaViewController.swift
Closes #621 with minor search UX improvements.
=> Search: Disable category change while searching 

.mailmap
This issue was highlighted with the following git changes:
https://git.kernel.org/pub/scm/git/git.git/commit/?id=9b274e28871b3e4a4109582a34625df5fddc91c8
=> mailmap: Fix mapping order

Sources/MediaCategoryCells/MovieCollectionViewCell.swift
Add corner radius according to design
=> MovieCollectionViewCell: Add corner radius according to design

SharedSources/MediaLibraryService.swift
=> MediaLibraryService: Handle dbReset correctly

Sources/AppearanceManager.swift, Sources/LocalNetworkConnectivity/VLCNetworkListCell.m, Sources/VLCStreamingHistoryCell.m
Update UITableViewCell highlight background colour according to design
=> Update UITableViewCell highlight background colour according to design

Sources/MediaCategories/MediaCategoryViewController.swift
Minor change, this could lead to assertions if the medialibrary is in debug.
=> MediaCategoryViewController: Request thumbnail only for video

Sources/VLCCloudServicesTableViewController.m
=> VLCCloudServicesTableViewController: Rename Cloud Services to iCloud

Sources/VLCCloudServicesTableViewController.m, Sources/VLCGoogleDriveController.m, Sources/VLCMovieViewController.m, Sources/VLCSettingsController.h, Sources/VLCStreamingHistoryCell.h
=> Fix various warnings

Sources/LocalNetworkConnectivity/VLCNetworkListCell.m
=> VLCNetworkListCell: Adapt to theme change

Podfile.lock, SharedSources/MediaLibraryService.swift
This depends on a MedialibraryKit update.
=> MediaLibraryService: Handle migration with completionHandlers

Resources/en.lproj/Localizable.strings, Sources/EditController.swift
Open to ideas for better strings!
Closes #647
=> EditController: Adapt deletion message for playlist

Apple-TV/AppleTVAppDelegate.m, Podfile, Podfile.lock, Sources/VLCAppDelegate.m, VLC.xcodeproj/project.pbxproj
=> Migrate Hockey to AppCenter

Sources/VLCMovieViewController.m
=> VLCMovieViewController: Handle iPad and notchless devices correctly

Resources/de.lproj/Localizable.strings, Resources/fr.lproj/Localizable.strings, Resources/he.lproj/Localizable.strings, Resources/ja.lproj/Localizable.strings, Resources/nl.lproj/Localizable.strings, Resources/pl.lproj/Localizable.strings, Resources/pt-BR.lproj/Localizable.strings, Resources/sk.lproj/Localizable.strings, Resources/sv.lproj/Localizable.strings, Resources/tr.lproj/Localizable.strings, Resources/uk.lproj/Localizable.strings, Resources/zh-Hant.lproj/Localizable.strings
=> Translations from 8.9
