Sources/MediaViewController.swift
Empty view now only appears when the library is empty, as one would expect it to
=> [UI] Fix empty view behavior

VLC.xcodeproj/xcshareddata/xcschemes/VLC-iOS.xcscheme
disable the test that is failing right now we will create a ticket for it and enable the test when reloading after adding of files works again
=> disable test until we fix the refresh after adding of files

Sources/VLCMovieViewController.m
The panrecognizer was set to disabled for non 360 videos
=> Fix broken gesture recognizers

SharedSources/VLCPlayingExternallyView.swift, Sources/VLCMovieViewController.m
When we refactored we didn't pass the movieView to the external screen when displaying externally
This worked well for chromecast and mirroring but sadly not for attaching an external screen via HDMI
Still need to test this with mirroring and chromecast
=> VLCMovieViewController: fix displaying on external screen via HDMI

Apple-TV/Playback/Playback Info/VLCPlaybackInfoSubtitlesFetcherViewController.m, Apple-TV/Playback/Playback Info/VLCPlaybackInfoTVCollectionViewCell.m, Apple-TV/VLCAboutViewController.m, Apple-TV/VLCRemotePlaybackViewController.m, Apple-TV/VLCSettingsViewController.m, README.md, Sources/VLCDropboxController.m
Fix a few warnings here and there. 
Most of them because of referencing a private variable from a block, I changed them by private properties which is a quite common point in most of the objc style guides (i.e. https://github.com/raywenderlich/objective-c-style-guide#variables)
=> Fix warnings

Podfile.lock, SharedSources/VLCMediaLibraryManager.swift
Re-enables thumbnails when adding a new media.
The issue was fixed by the medialibrary changes.
=> Re-enable thumbnails(closes #293)

Sources/VLCLibraryViewController.m
closes [#313](https://code.videolan.org/videolan/vlc-ios/issues/313)
Tested this change on an iPad as well for the drag and drop, this doesn't seem to affect it.
I may have missed some DnD cases.
=> VLCLibraryViewController: Make reordering possible only in a folder

Resources/VLCMovieViewController~ipad.xib, Resources/VLCMovieViewController~iphone.xib, Resources/en.lproj/Localizable.strings, SharedSources/PlayingExternallyView.swift, Sources/VLCMovieViewController.m, VLC.xcodeproj/project.pbxproj
This moves the PlayingExternally layout into one xib, this has the advantage that we can use autolayout at least for that view and don't, in the future, update the screen in the iPhone version and forget the iPad xib. It also displays the movie title now as playing externally title which doesn't lead to colliding text.
=> Fix overlapping title

SharedSources/VLCMediaLibraryManager.swift, Sources/VLCAppDelegate.m, Sources/VLCMediaFileDiscoverer.h, VLC-iOS-Bridging-Header.h
This allows monitoring of changes in the Documents files from external
apps.
Additionally changes `mediaFilesFoundRequiringAdditionToStorageBackend`
to optional since the new medialibrary doesn't need it.
=> Move VLCMediaFileDiscovererDelegate to VLCMediaLibraryManager

Sources/VLCOneDriveController.h, Sources/VLCOneDriveController.m, Sources/VLCOneDriveTableViewController.m
During the `goBack` method, we're only setting the parentID. This led to navigation failure when the hierarchy had more than 3 folders. With this patch, we now load the `parentItem`  that loads its `parentReference`.
=> Onedrive: Fix hierarchy navigation issue

Sources/VLCActionSheet/VLCActionSheet.swift
This adds a dismiss animation so that the user isn't flashed by a
flashed by the default animation.
This improves the overall animation of the action sheet dismissal.
`4e58a56` Could have been into a separate PR but with the "tidy-upping" I found it can be more trouble.
If really needed, I can make a separate PR.
=> Actionsheet: Add dismiss animation

Resources/en.lproj/Localizable.strings, SharedSources/MediaLibraryModel/AlbumModel.swift, SharedSources/MediaLibraryModel/ArtistModel.swift, SharedSources/MediaLibraryModel/AudioModel.swift, SharedSources/MediaLibraryModel/GenreModel.swift, SharedSources/MediaLibraryModel/PlaylistModel.swift, SharedSources/MediaLibraryModel/ShowEpisodeModel.swift, SharedSources/MediaLibraryModel/VideoModel.swift, Sources/Coordinators/SortModel.swift, Sources/MediaCategories/MediaCategoryViewController.swift, Sources/VLCActionSheet/VLCActionSheet.swift
Use `VLCActionSheet` to display sort alert.
While integrating VLCActionSheet, I relealized that it would be simpler to pass an array of supported sorting criterias.
Indeed, this way we won't encounter index syncronization issues and it will make the global usage easier.
A follow-up ticket to this PR would be to polish it with the new design(adding icons that we currently don't have for every criteria).
Closes [#415](https://code.videolan.org/videolan/vlc-ios/issues/415).
=> Sort: Use VLCActionSheet

Sources/Coordinators/AppCoordinator.swift
In the case of a fresh install of the app or even an empty or small
library, the tabBarController didn't have the time to finish to present
the VC therefore failing the check in `medialibraryDidFinishMigration`.
Removing the migrationViewController directly resolve this issue.
In the case of a fresh install of the app or even an empty or small library, the tabBarController didn't have the time to finish to present the VC, therefore, failing the check in `medialibraryDidFinishMigration`.
Removing the migrationViewController directly resolve this issue.
=> AppCoordinator: Dismiss directly migrationViewController

Apple-TV/VLCServerListTVViewController.m
This is a quick fix/additions to add a port textfield when connecting to a discovered server.
I'm not sure if this is really needed but, it could be interesting to have for consistency with iOS.
Later on, it could be interesting to refactor this part of the code as well.
Preview:
=> VLCServerListTVViewController: Add port textfield in server connections

SharedSources/MediaLibraryModel/AlbumModel.swift, SharedSources/MediaLibraryModel/ArtistModel.swift, SharedSources/MediaLibraryModel/AudioModel.swift, SharedSources/MediaLibraryModel/CollectionModel.swift, SharedSources/MediaLibraryModel/GenreModel.swift, SharedSources/MediaLibraryModel/MediaLibraryBaseModel.swift, SharedSources/MediaLibraryModel/MediaModel.swift, SharedSources/MediaLibraryModel/PlaylistModel.swift, SharedSources/MediaLibraryModel/ShowEpisodeModel.swift, SharedSources/MediaLibraryModel/VideoModel.swift, Sources/VLCEditController.swift
This PR moves the add to playlist logic during the edit into the models.
This allows to have specific actions for different models.
Additionally, this integration only creates new playlist with a selection.
The ability to add to existing playlists will be added later on with the UI.
=> VLCEditController: Move add to playlist logic into models

SharedSources/MediaLibraryService.swift
By caching it on the start on the medialibrary, we need to update the value when successfully migrated, else it will continue to migrate on each new media parsing.
=> MediaLibraryService: Migration: Update didMigrate value

Sources/AppearanceManager.swift
In the case of VLCMovieViewController, we need to propagate it in order
to always set the preferred status bar style to .lightContent
In the case of VLCMovieViewController, we need to propagate it in order to always set the preferred status bar style to `.lightContent`
=> VLCTabBarCoordinator: Propagate childForStatusBarStyle

Resources/Xib/AddToPlaylist/AddToPlaylistView.xib, Resources/en.lproj/Localizable.strings, Sources/AddToPlaylistViewController.swift, Sources/MediaCategories/MediaCategoryViewController.swift, Sources/MediaCategoryCells/MediaCollectionViewCell.swift, Sources/VLCEditController.swift, VLC.xcodeproj/project.pbxproj
This adds the possibility to add any model to an existing playlist.
For now I went for a basic design, it should later be changed with Louis's input.
Additionnaly, the addition of the playlist from collections(genre, artist) will be done in a separate PR.
=> Add to existing playlists

Resources/Xib/MiniPlayer/AudioMiniPlayer.xib
There was an extra pixel with the progressView since UIKit doesn't seem to handle it well.
before:
after:
=> AudioMiniPlayer: Reduce infoStackView height to align with artwork

Sources/Coordinators/AppCoordinator.swift, Sources/VLCPlayerDisplayController.m
With the hierarchy changes from `4f4e0033`, the view on the controller stopped receiving callbacks for rotation(transitions). This led to the miniplayer being broken on rotation.
Additionally, minor cosmetic and syntax commits.
=> VLCPlayerDisplayController: Fix rotation resizing

Sources/MediaCategoryCells/GenreCollectionViewCell.swift, Sources/MediaCategoryCells/MediaCollectionViewCell.swift, Sources/MediaCategoryCells/MovieCollectionViewCell.swift, Sources/MediaEditCell.swift
This fixes the current thumbnailing which didn't work all the time because of the wrong path.
=> Thumbnail path fix

Sources/ActionSheet/ActionSheet.swift, Sources/ActionSheet/ActionSheetCell.swift, Sources/ActionSheet/ActionSheetSectionHeader.swift, Sources/MediaCategories/MediaCategoryViewController.swift, Sources/VLCActionSheet/VLCActionSheet.swift, Sources/VLCCloudSortingSpecifierManager.swift, Sources/VLCRendererDiscovererManager.swift, Sources/VLCSettingsSheetCell.swift, Sources/VLCSettingsSpecifierManager.swift, VLC.xcodeproj/project.pbxproj
This fixes the sort action sheet not showing up after a selection.
Also, a bit of name refactoring on the ActionSheet*.
Related ticket: https://code.videolan.org/videolan/vlc-ios/issues/438.
=> Fix sort actionsheet

SharedSources/MediaLibraryModel/MediaModel.swift, SharedSources/MediaLibraryService.swift, Sources/Coordinators/AppCoordinator.swift, Sources/MediaCategories/MediaCategoryViewController.swift, Sources/VLCAppDelegate.m, Sources/VLCConstants.h, Sources/VLCSettingsController.m
this adds corespotlight to the app. 
It sets isspotlight enabled on startup 
it updates corespotlight when an item is played. 
it correctly handles a tap on a corespotlight item and starts playback of that item
it also observes the userdefault for passcode and sets is spotlightenabled to false when it is set
=> Add Corespotlight

SharedSources/MediaLibraryService.swift
This fixes issue [#471](https://code.videolan.org/videolan/vlc-ios/issues/471).
As the documentation states:
``` 
* @param includeAll If true, all artists including those without album
*                   will be returned. If false, only artists which have
*                   an album will be returned.
```
We now set `includeAll` to false. Ideally, as Hugo mentioned this could be a setting to add later on.
Sadly, this brings up another issue which is the artist discovery.
For example, when importing an album with multiple artist and featuring, this won't be taken into account directly leading to the issue we had before this patch.
A follow-up ticket should be open when this is merged.
=> MediaLibraryService: Artists: Set all to false by default

SharedSources/MediaLibraryModel/AlbumModel.swift, SharedSources/MediaLibraryModel/ArtistModel.swift, SharedSources/MediaLibraryModel/GenreModel.swift, SharedSources/MediaLibraryService.swift
This fixes that artists, genre and albums were not deleted. We now added observers for deletion
=> Collectionmodels: Delete object in file when deletion was observed

Podfile, Podfile.lock, Resources/en.lproj/Localizable.strings, SharedSources/MediaLibraryModel/AlbumModel.swift, SharedSources/MediaLibraryModel/ArtistModel.swift, SharedSources/MediaLibraryModel/MediaModel.swift, Sources/MediaCategoryCells/MediaCollectionViewCell.swift
In the medialibrary, there is a specific ID for unknown and various artist.
This uses them in order to show the correct localization for them.
=> MediaCollectionViewCell: Handle unknown and various artist

Apple-TV/VLCRemotePlaybackViewController.m, Resources/web/jquery.fileupload.js, Sources/VLCConstants.h, Sources/VLCHTTPConnection.m, Sources/VLCHTTPFileDownloader.m, Sources/VLCHTTPUploaderController.m
This might not be the ideal solution since I have a very limited knowledge on our HTTP-fun(JS, JQuery, ...) side.
With this patch, we now send the whole path in the `MultipartMessageHeader` which makes thinks easier on the application side to handle the file structure.
Testing are welcome!
Closes [#381](https://code.videolan.org/videolan/vlc-ios/issues/381) and partially avoids [medialibrary#74](https://code.videolan.org/videolan/medialibrary/issues/74).
=> HTTP Import: Respect folder structure

Resources/en.lproj/Localizable.strings, SharedSources/MediaLibraryModel/AlbumModel.swift, SharedSources/MediaLibraryModel/ArtistModel.swift, SharedSources/MediaLibraryModel/GenreModel.swift, SharedSources/MediaLibraryModel/MediaLibraryBaseModel.swift, SharedSources/MediaLibraryModel/PlaylistModel.swift, SharedSources/MediaLibraryModel/ShowEpisodeModel.swift, SharedSources/MediaLibraryModel/TrackModel.swift, SharedSources/MediaLibraryModel/VideoModel.swift, Sources/ActionSheet/ActionSheet.swift, Sources/ActionSheet/ActionSheetSectionHeader.swift, Sources/ActionSheet/ActionSheetSortSectionHeader.swift, Sources/MediaCategories/MediaCategoryViewController.swift, VLC.xcodeproj/project.pbxproj
This integrate the possibility to change the asc/desc sorting order with the following design from Figma: 
With this header, having a landscape orientation is not great since it cover quite a bit of space.
We should iterate on this.
Closes [#414](https://code.videolan.org/videolan/vlc-ios/issues/414)
=> Sort: Handle ascending and descending sort

Sources/MediaViewControllers/AudioViewController.swift
To be in line with other platforms, set audio categories as:
Artist, Album, Tracks, Genre
=> AudioViewController: Rearrange categories order

Sources/ActionSheet/ActionSheet.swift, Sources/ActionSheet/ActionSheetSortSectionHeader.swift, Sources/Coordinators/SortModel.swift, Sources/MediaCategories/MediaCategoryViewController.swift, Sources/MediaViewControllers/MediaViewController.swift
This adds a nice small shortcut to change the sorting order.
After a discussion with Alex, I found this feature to be nice to have, so I decided to integrate it. 😅
=> VLCMediaViewController: Add long press to sort order

Sources/Coordinators/AppCoordinator.swift
initializing the tabbarcoordinator before we setup the childViewControllers leads to a 6th tab
Likely caused by tabBarController.addChild(playerController) which contains our miniplayer
instantiating the tabbarcoordinator lazily fixes it
(closes #539)
=> AppCoordinator: Fix invisible 6th tab in TabBar

Sources/VLCDropboxController.m
It seems that this was removed by 3a9b4d86.
Without this method, we are never getting the file listing.
=> VLCDropboxController: Re-integrate currentListFiles

Podfile, Podfile.lock, Sources/VLCDropboxController.m
Closes [#562](https://code.videolan.org/videolan/vlc-ios/issues/562).
Also bump the official sdk to 3.10.0 that seems to bring more stability, security, and bug fixes.
=> VLCDropboxController: Encode destination path with URLPathAllowedCharacterSet

SharedSources/MediaLibraryModel/MediaModel.swift, SharedSources/MediaLibraryModel/TrackModel.swift, SharedSources/MediaLibraryModel/VideoModel.swift, SharedSources/MediaLibraryService.swift
First, this adds the medialibrary object modified callbacks to the `MediaLibraryService`.
Secondly, this integrates the modified callbacks to the MediaModels(Video, Tracks) since for now, we only expose the ability to change metadata to MediaModels.
Additionally, some minor cosmetic/readability patches.
=> MediaModels: Handle MediaModified callback

Sources/MediaCategoryCells/MovieCollectionViewCell.swift, Sources/MediaCategoryCells/MovieCollectionViewCell.xib
This adjusts the height for **MovieCollectionViewCells** by:
- Removing extra 24 padding
- Increasing compression resistance of the title label
- Decrease title to 14
Tests are welcome, I have tested this on:
- iPhone 4s - iOS 9
- iPhone 8 - iOS 12
- iPhone X - iOS 12
- iPad Pro (12.9) 3rd gen - iOS 12
**Comparaison screenshots:**
Left with new changes - right master.
With long titles
=> MovieCollectionViewCell: Adjust height

Sources/VLCPlaybackController.h, Sources/VLCPlaybackController.m, Sources/VLCPlayerDisplayController.m
This makes the property playerIsSetup accessible in order to check if the player is setup.
Indeed for the case of the miniplayer, we were basing the shown
state on the return values of libvlc `willPlay` and `isPlaying`.
This led to have inconsistency because of synchronization issues.
(closes #472)
=> VLCPlayerDisplayController: Miniplayer: Check is player is setup

SharedSources/MediaLibraryModel/CollectionModel.swift
This fixes the deletion on collections such as Artist, Albums.
=> CollectionModel: Fix deletion for VLCMLMedias

SharedSources/MediaLibraryModel/GenreModel.swift, SharedSources/MediaLibraryModel/MediaLibraryBaseModel.swift, SharedSources/MediaLibraryModel/MediaModel.swift, SharedSources/MediaLibraryModel/TrackModel.swift, SharedSources/MediaLibraryModel/VideoModel.swift
This fixes the case where Genres were not updated on modification.
For now this fixes only addition since media deletion doesn't seem to be triggering didModifyGenres.
Depending on the medialibrary schedule, a workaround might be needed.
=> GenreModel: Observe didModifyGenres

Sources/URLHandler.swift, Sources/VLCAppDelegate.m, Sources/VLCConstants.h
In the case where the user would cancel the login of Dropbox, we were launching the media player.
=> Dropbox: Handle login cancel case correctly

Sources/LocalNetworkConnectivity/VLCServerListViewController.m
By setting the estimatedRowHeight to 0, we disable estimated heights.
Indeed, it seems that the height was wrongly estimated by the system before.
(closes #627)
=> VLCServerListViewController: localNetworkTableView: Fix cell sizing

SharedSources/ServerBrowsing/HTTP/VLCLocalNetworkServiceBrowserHTTP.m
Use wifi icon to represent other VLC-iOS instances over http service.
=> VLCLocalNetworkServiceBrowserHTTP: Use same icon as wifi

SharedSources/VLCMetadata.m
Fix `checkIsAudioOnly` by using `numberOfVideoTracks` from the mediaPlayer.
This fixes certain cases where the media was wrongly detected.
This only affects tvOS.
=> VLCMetadata: checkIsAudioOnly: Use numberOfVideoTracks

Sources/MediaCategoryCells/MovieCollectionViewCell.xib
We should respect the aspect ratio of the media content.
For example, this can lead audio Playlists to have stretched image.
=> MovieCollectionViewCell: Thumbnail: Set contentMode to aspectToFill

Sources/VLCMovieViewController.m, Sources/VLCPlaybackService.h, Sources/VLCPlaybackService.m
In the case where we're playling a wide video(e.g. 21:9). This adapts the movieView's constraints to the notch.
Closes #634
=> VLCMovieViewController: Adapt movieView to notch for wide video

Sources/MediaCategories/MediaCategoryViewController.swift, Sources/VLCPlaybackService.h, Sources/VLCPlaybackService.m, Sources/VLCPlayerDisplayController.m
For now, this hide the mini player when entering edit mode.
This uses a behaviour already in place inside `VLCPlayerDisplayController`. 
Therefore, this doesn't change from the old behaviour.
This might not be ideal, even could be considered as a workaround, but I believe this is compromise we could agree on for the 3.2.0 release.
Closes #626
=> MediaCategoryViewController: Hide MiniPlayer on Edit

Sources/VLCMovieViewController.m
Run `updateTimeDisplayButton` on the main thread when called by `UpdateDefaults`.
=> VLCMovieViewController: Perform layout related method on main thread
